#!/usr/bin/env python3

import sys
from parser import read_friendships, read_conspiracies
from links import links_mode
from plots import plots_mode

def print_help():
    print("USAGE")
    print("./game_of_stones [--links FR P1 P2 | --plots FR CR n]")
    print("DESCRIPTION")
    print("FR     file containing friendship relations between people")
    print("Pi     name of someone in the friendships file")
    print("CR     file containing conspiracies intentions")
    print("n      maximum length of friendship paths")

def main():
    if len(sys.argv) < 2 or sys.argv[1] == "--help":
        print_help()
        sys.exit(0 if sys.argv[1] == "--help" else 84)

    mode = sys.argv[1]

    if mode == "--links":
        if len(sys.argv) != 5:
            print("Error: Invalid number of arguments for --links", file=sys.stderr)
            sys.exit(84)
        friends_file = sys.argv[2]
        person1 = sys.argv[3]
        person2 = sys.argv[4]
        links_mode(friends_file, person1, person2)

    elif mode == "--plots":
        if len(sys.argv) != 5:
            print("Error: Invalid number of arguments for --plots", file=sys.stderr)
            sys.exit(84)
        friends_file = sys.argv[2]
        plots_file = sys.argv[3]
        try:
            max_depth = int(sys.argv[4])
            if max_depth < 0:
                raise ValueError
        except ValueError:
            print("Error: The maximum depth must be a positive integer", file=sys.stderr)
            sys.exit(84)
        plots_mode(friends_file, plots_file, max_depth)

    else:
        print("Error: Unknown mode", file=sys.stderr)
        sys.exit(84)

if __name__ == "__main__":
    main()